/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doctorwho_ood_TheGift */

#ifndef _Included_com_doctorwho_ood_TheGift
#define _Included_com_doctorwho_ood_TheGift
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_doctorwho_ood_TheGift
 * Method:    invokeNativeFunction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_doctorwho_ood_TheGift_invokeNativeFunction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
