/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_app_Main */

#ifndef _Included_com_example_app_Main
#define _Included_com_example_app_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_app_Main
 * Method:    invokeNativeFibo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_app_Main_invokeNativeFibo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_app_Main
 * Method:    invokeCallbackFibo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_app_Main_invokeCallbackFibo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
