/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_app_DoctorWho */

#ifndef _Included_com_example_app_DoctorWho
#define _Included_com_example_app_DoctorWho
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_app_DoctorWho
 * Method:    invokeNativeFunction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_app_DoctorWho_invokeNativeFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
